#!/bin/bash
sudo -u root bash << EOF
cp /home/xilinx/firmware/RPU_libmetal_amp_demo.elf /lib/firmware
echo RPU_libmetal_amp_demo.elf > /sys/class/remoteproc/remoteproc0/firmware
echo start > /sys/class/remoteproc/remoteproc0/state
./libmetal_amp_demo
echo stop > /sys/class/remoteproc/remoteproc0/state
